version: "2"
run:
  go: "1.24"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - dupword
    - exhaustive
    - nestif
    - nilnesserr
    - nilnil
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - usestdlibvars
    - usetesting
  settings:
    unused:
      field-writes-are-uses: false
      exported-fields-are-used: false
      local-variables-are-used: false

    errcheck:
      check-type-assertions: false
      check-blank: true
    nestif:
      min-complexity: 5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: 'unused-parameter:'
      - linters:
          - revive
        text: var-naming
      - linters:
          - errcheck
        path: _test\.go$
        source: \.(string|int|float64|bool|interface{})\)
